
services:
  app:
    build:
      context: ./docker/8.4
      dockerfile: Dockerfile
    image: 'tbitencourt/php-fpm:8.4'
    container_name: 'assessment-symfony-pokemontcg-app'
    ports:
      - "9000:9000"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html'
    networks:
      - app-network
    depends_on:
      - database
  webserver:
    image: 'nginx:alpine'
    container_name: 'assessment-symfony-pokemontcg-webserver'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/app.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - app-network
    depends_on:
      - database
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    container_name: 'assessment-symfony-pokemontcg-db'
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - tbitencourt-dbdata:/var/lib/postgresql/data:rw
    networks:
      - app-network
###< doctrine/doctrine-bundle ###
networks:
  app-network:
    driver: bridge
volumes:
###> doctrine/doctrine-bundle ###
  tbitencourt-dbdata:
    driver: local
###< doctrine/doctrine-bundle ###
